// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5Kzm8czqjbVg7ZU4Isw4wnJye0MEWWv0',
    appId: '1:87460558525:web:97473f4fc114d017c469d4',
    messagingSenderId: '87460558525',
    projectId: 'stream-5918d',
    authDomain: 'stream-5918d.firebaseapp.com',
    storageBucket: 'stream-5918d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtuv-z6A-ExoYSRYlrDrjTjRvVUDCbWls',
    appId: '1:87460558525:android:6fdd2957f41e52f0c469d4',
    messagingSenderId: '87460558525',
    projectId: 'stream-5918d',
    storageBucket: 'stream-5918d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy6VEe3Lw-c9n-ARWrnlXIj1TU8Udsm2c',
    appId: '1:87460558525:ios:3968acf283837e23c469d4',
    messagingSenderId: '87460558525',
    projectId: 'stream-5918d',
    storageBucket: 'stream-5918d.appspot.com',
    iosClientId: '87460558525-f5fishte2701gk3olm4ljl5hp19kmjlh.apps.googleusercontent.com',
    iosBundleId: 'com.example.stream',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy6VEe3Lw-c9n-ARWrnlXIj1TU8Udsm2c',
    appId: '1:87460558525:ios:daf4680595206df9c469d4',
    messagingSenderId: '87460558525',
    projectId: 'stream-5918d',
    storageBucket: 'stream-5918d.appspot.com',
    iosClientId: '87460558525-t4ta8clv8mcm7poq8oag12v3oi4e4a9u.apps.googleusercontent.com',
    iosBundleId: 'com.example.stream.RunnerTests',
  );
}
